### ISSUE TITLE
Code Audit via sortie (irc #osdev)

### ISSUE THREAD

**Issue by AndrewBC** [thepowersgang/acess2#5]
<sortie> thePowersGang: According to a grep of unsigned char in my libc, which isn't entirely finished with these fixes, you probably need to audit: strcasecmp, memset, strncmp, memrchr, strchrnul, strcmp, stresep, strrchr, memchr, strncasecmp, memccpy, memcmp, fputc family, fgetc family, btowc, and wctob. (If you have them)

**Comment by sortie** [comment]
Sortie already posted issue #6 after this report.

**Comment by AndrewBC** [comment]
Indeed!
